config/routes.rb
Rails.application.routes.draw do
  # Static pages routes
  match '/home', to: 'static_pages#home', via: [:get]
  match '/help', to: 'static_pages#help', via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/contact', to: 'static_pages#contact', via: [:get]
  match '/signIn', to: 'static_pages#signIn', via: [:get]

  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/signIn'

  # Users/signup routes
  get 'users/new'
  match '/signup', to: 'users#new', via: [:get]

  # Root
  root "static_pages#home" 

  resources :chats
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :bigint           not null, primary key
#  text       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Chat < ApplicationRecord
  belongs_to :user

  validates :text, length: {in: 2..140}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string
#  email           :string
#  username        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#
class User < ApplicationRecord
  has_many :chats
  has_secure_password

  before_save { |user| user.email = email.downcase }

  # Name validation: 
  #   Must be non-blank
  #   Must be betwen 3 and 40 characters long
  #   Must contain only valid characters
  validates(:name,
    presence: true,
    length: { minimum: 3, maximum: 40 } 
  )

  # Email validation:
  #   Must be non-blank
  #   Must be in a valid format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, 
    presence: true, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  )

  # Username validation:
  #   Must be non-blank
  #   Must be unique
  validates(:username, 
    presence: true,
    uniqueness: { case_sensitive: false }
  )

  # Password validation:
  #   Must be non-blank
  #   Must be at least 6 characters long
  validates(:password,
    presence: true,
    length: { minimum: 6 }
  )
  
  # Password confirmation validation:
  #   Must be non-blank
  validates(:password_confirmation,
    presence: true
  )

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: "Chat was successfully created." }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:text, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def signIn
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User successfully created!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, 
      notice: 'User ''@user.username'' was successfully deleted.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :username) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title) 
    base_title = "Chatter"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for email, options = {}
#    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
#    gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png"
#    image_tag(gravatar_url, alt: "Gravatar not found", class: "gravatar")
    
    options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
    id = Digest::MD5::hexdigest email.strip.downcase
    url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
    options.delete :size
    image_tag url, options
  end
end

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.text %></td>
        <td><%= chat.user_id %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to "Home", chats_path %>
</p>

<p>
  <strong>Text:</strong>
  <%= @chat.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @chat.user_id %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
  </nav>
  
  <small>
    <p>Based on <a href="http://railstutuorial.org/">Rails Tutorial</a> by Michael Hartl</p>
    <p>&#169;2021, Imperial Sword Creations <br/>All rights reserved.</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<body>
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container" style="float: right">
        <%= link_to "Chatter", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Sign In", signIn_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <div class="container">
    <h1>Welcome, 
      <% if @user.nil? %>
        <%= "Chatterbox!" %>
      <% else %>
        <%= @user.username %>!
      <% end %>
    </h1>
  </div>
</body>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.je".</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Chatter</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>We hope you're enjoying Chatter!  If you have
any questions or comments, please feel free to 
contact us at: {contact_info}</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Chatter!</h1>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= image_tag "rails.jpeg", alt: "Rails" %>

app/views/static_pages/signIn.html.erb
<%= provide(:title, 'Sign In') %>
<div>
  <h1><%= yield(:title) %></h1>
  <form action="#" method="post">
    <label for="userid">User Name</label>
    <input type="text" id="userid" name="userid"><br/>
    <label for="password">Password</label>
    <input type="password" id="password" name="password"><br/>
    <input type="submit" value="Submit">
  </form>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
   
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Create account" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Active Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td>&nbsp;<%= link_to 'Show', user_path(user) %> |</td>
        <td>&nbsp;<%= link_to 'Edit', edit_user_path(user) %> |</td>
        <td>&nbsp;<%= link_to 'Delete', 
                              user, 
                              method: :delete, 
                              data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create new user", signup_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up to become a Chatterbox!</h1>

<div class="row">
  <div class="span6 offset3">
    <!--  <%= render 'form', user: @user %> -->

    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %><br/>

      <%= f.label :email %>
      <%= f.text_field :email %><br/>

      <%= f.label :username %>
      <%= f.text_field :username %><br/>

      <%= f.label :password %>
      <%= f.password_field :password %><br/>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %><br/><br/>

      <%= f.submit "Create account" %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.username ) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user.email %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p id="notice"><%= notice %></p>

<p>
  <%= link_to "Home", users_path %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</p>